name: Github Packages Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/

      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run build

      - name: NPM Publish
        run: npm publish
