name: Pull Request Check ESLint and Tests

on:
  pull_request:
    branches: [master]

jobs:
  eslint_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@simple-ti'

      - name: NPM Install
        run: npm run full-install

      - name: NPM ESLint
        run: npm run eslint

      - name: NPM Test
        run: npm test
